import api from './api';

export type ReportType = 'MLR' | 'MLEF' | 'PMR' | 'CERTIFICATE_OF_RECEIPT';
export type ReportStatus = 'DRAFT' | 'FINALIZED' | 'DISPATCHED' | 'RECEIPT_CONFIRMED';


export interface ForensicReportDto {
  id?: number;
  reportType: ReportType;
  status: ReportStatus;
  versionNumber?: number;
  caseType: 'CLINICAL' | 'POSTMORTEM';
  mlefRecordId?: number;
  pmSerialNo?: number;
  serialNo: string;
  courtName?: string;
  courtCaseNo?: string;
  policeStation?: string;
  policeRefNo?: string;
  dateOfTrial?: string;
  examinationDate?: string;
  opinion?: string;
  detailsJson?: string;
  doctorName?: string;
  doctorDesignation?: string;
  doctorSlmcNo?: string;
  draftDate?: string;
  finalizedDate?: string;
  dispatchedDate?: string;
  receiptConfirmedDate?: string;
  parentReportId?: number;
  amendmentReason?: string;
  createdAt?: string;
  updatedAt?: string;
  subjectName?: string;
  subjectIdentifier?: string;
}

export interface ReportStatusUpdateDto {
  status: ReportStatus;
  notes?: string;
}

export interface OverdueReportItem {
  caseType: 'CLINICAL' | 'POSTMORTEM';
  caseId: number;
  referenceNo: string;
  subjectName: string;
  examinationDate: string;
  daysOverdue: number;
  assignedDoctor: string;
}

export interface UpcomingCourtCaseItem {
  reportId?: number;
  caseType: string;
  caseId: number;
  courtName: string;
  courtCaseNo: string;
  dateOfTrial: string;
  daysUntilTrial: number;
  subjectName: string;
}

export interface PendingDispatchItem {
  reportId: number;
  reportType: ReportType;
  serialNo: string;
  caseType: string;
  caseId: number;
  courtName?: string;
  courtCaseNo?: string;
  finalizedDate: string;
  doctorName?: string;
}

export interface ReportNotificationDto {
  overdueReports: OverdueReportItem[];
  upcomingCourtDates: UpcomingCourtCaseItem[];
  pendingDispatches: PendingDispatchItem[];
}

export interface DailyCaseItem {
  caseType: 'CLINICAL' | 'POSTMORTEM';
  caseId: number;
  referenceNo: string;
  subjectName: string;
  policeStation: string;
  dateTimeExamined: string;
  doctorName: string;
  status: string;
}

export interface DailyReportDto {
  date: string;
  totalClinicalCases: number;
  totalPostmortemCases: number;
  totalCases: number;
  items: DailyCaseItem[];
}

export interface DoctorWorkloadItem {
  doctorName: string;
  clinicalCount: number;
  postmortemCount: number;
  totalCount: number;
}

export interface StationDistributionItem {
  policeStation: string;
  count: number;
}

export interface MonthlyReportDto {
  year: number;
  month: number;
  monthName: string;
  totalClinical: number;
  totalPostmortem: number;
  totalFinalized: number;
  totalDispatched: number;
  doctorWorkload: DoctorWorkloadItem[];
  stationDistribution: StationDistributionItem[];
}

export interface PendingReportDto {
  overdueDraftsCount: number;
  pendingDispatchesCount: number;
  overdueDrafts: OverdueReportItem[];
  pendingDispatches: PendingDispatchItem[];
}

export interface CourtReportDto {
  upcomingTrialsCount: number;
  pendingDispatchesCount: number;
  receiptConfirmedCount: number;
  upcomingTrials: UpcomingCourtCaseItem[];
  pendingDispatches: PendingDispatchItem[];
}

export interface StatisticalReportDto {
  totalCases: number;
  genderDistribution: Record<string, number>;
  ageDistribution: Record<string, number>;
  bodilyHarmFrequencies: Record<string, number>;
  substanceStats: Record<string, number>;
  caseTypeBreakdown: Record<string, number>;
}

export const reportService = {
  autoGenerateDraft: async (caseType: string, caseId: number, reportType: ReportType = 'MLR'): Promise<ForensicReportDto> => {
    const response = await api.post(`/reports/generate?caseType=${caseType}&caseId=${caseId}&reportType=${reportType}`);
    return response.data;
  },
  save: async (data: ForensicReportDto): Promise<ForensicReportDto> => {
    const response = await api.post('/reports', data);
    return response.data;
  },
  getById: async (id: number): Promise<ForensicReportDto> => {
    const response = await api.get(`/reports/${id}`);
    return response.data;
  },
  getAll: async (status?: ReportStatus): Promise<ForensicReportDto[]> => {
    const response = await api.get('/reports', { params: { status } });
    return response.data;
  },
  getReportsForCase: async (caseType: string, caseId: number): Promise<ForensicReportDto[]> => {
    const response = await api.get(`/reports/case/${caseType}/${caseId}`);
    return response.data;
  },
  updateStatus: async (id: number, status: ReportStatus, notes?: string): Promise<ForensicReportDto> => {
    const response = await api.patch(`/reports/${id}/status`, { status, notes });
    return response.data;
  },
  amendReport: async (id: number, reason: string, data: ForensicReportDto): Promise<ForensicReportDto> => {
    const response = await api.post(`/reports/${id}/amend?reason=${encodeURIComponent(reason)}`, data);
    return response.data;
  },
  getNotificationWidgetData: async (): Promise<ReportNotificationDto> => {
    const response = await api.get('/reports/dashboard-notifications');
    return response.data;
  },
  getDailyReport: async (date?: string): Promise<DailyReportDto> => {
    const response = await api.get('/reports/analytics/daily', { params: { date } });
    return response.data;
  },
  getMonthlyReport: async (year?: number, month?: number): Promise<MonthlyReportDto> => {
    const response = await api.get('/reports/analytics/monthly', { params: { year, month } });
    return response.data;
  },
  getPendingReport: async (): Promise<PendingReportDto> => {
    const response = await api.get('/reports/analytics/pending');
    return response.data;
  },
  getCourtReport: async (): Promise<CourtReportDto> => {
    const response = await api.get('/reports/analytics/court');
    return response.data;
  },
  getStatisticalReport: async (): Promise<StatisticalReportDto> => {
    const response = await api.get('/reports/analytics/statistics');
    return response.data;
  }
};
