import React, { useEffect, useState } from 'react';
import { reportService, type ForensicReportDto, type ReportType, type ReportStatus } from '../../services/report.service';
import { generateReportPdf, printReportPdf, getReportPdfBlobUrl } from './pdfGenerator';
import { X, FileText, Download, Printer, Eye, Edit3, CheckCircle, Send, CheckSquare, RefreshCw, Loader2, AlertCircle } from 'lucide-react';

interface ReportGeneratorModalProps {
  isOpen: boolean;
  onClose: () => void;
  caseType: 'CLINICAL' | 'POSTMORTEM';
  caseId: number;
  existingReport?: ForensicReportDto | null;
  onReportSaved?: () => void;
}

export const ReportGeneratorModal: React.FC<ReportGeneratorModalProps> = ({
  isOpen,
  onClose,
  caseType,
  caseId,
  existingReport,
  onReportSaved,
}) => {
  const [reportType, setReportType] = useState<ReportType>(caseType === 'POSTMORTEM' ? 'PMR' : 'MLR');
  const [viewMode, setViewMode] = useState<'FORM' | 'PREVIEW'>('FORM');
  const [pdfPreviewUrl, setPdfPreviewUrl] = useState<string | null>(null);

  const [formData, setFormData] = useState<Partial<ForensicReportDto>>({
    courtName: '',
    courtCaseNo: '',
    policeStation: '',
    policeRefNo: '',
    dateOfTrial: '',
    opinion: '',
    doctorName: '',
    doctorDesignation: '',
    doctorSlmcNo: '',
  });
  const [currentReport, setCurrentReport] = useState<ForensicReportDto | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [saving, setSaving] = useState<boolean>(false);
  const [amendReason, setAmendReason] = useState<string>('');
  const [showAmendInput, setShowAmendInput] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const getCombinedReportData = (): ForensicReportDto | null => {
    if (!currentReport) return null;
    return {
      ...currentReport,
      reportType,
      courtName: formData.courtName,
      courtCaseNo: formData.courtCaseNo,
      policeStation: formData.policeStation,
      policeRefNo: formData.policeRefNo,
      dateOfTrial: formData.dateOfTrial,
      opinion: formData.opinion,
      doctorName: formData.doctorName,
      doctorDesignation: formData.doctorDesignation,
      doctorSlmcNo: formData.doctorSlmcNo,
    };
  };

  useEffect(() => {
    if (!isOpen) return;

    const initReport = async () => {
      setLoading(true);
      setError(null);
      try {
        if (existingReport) {
          setCurrentReport(existingReport);
          setReportType(existingReport.reportType);
          setFormData({
            courtName: existingReport.courtName || '',
            courtCaseNo: existingReport.courtCaseNo || '',
            policeStation: existingReport.policeStation || '',
            policeRefNo: existingReport.policeRefNo || '',
            dateOfTrial: existingReport.dateOfTrial || '',
            opinion: existingReport.opinion || '',
            doctorName: existingReport.doctorName || '',
            doctorDesignation: existingReport.doctorDesignation || '',
            doctorSlmcNo: existingReport.doctorSlmcNo || '',
          });
        } else {
          // Auto-generate draft from case data
          const draft = await reportService.autoGenerateDraft(caseType, caseId, reportType);
          setCurrentReport(draft);
          setFormData({
            courtName: draft.courtName || '',
            courtCaseNo: draft.courtCaseNo || '',
            policeStation: draft.policeStation || '',
            policeRefNo: draft.policeRefNo || '',
            dateOfTrial: draft.dateOfTrial || '',
            opinion: draft.opinion || '',
            doctorName: draft.doctorName || '',
            doctorDesignation: draft.doctorDesignation || '',
            doctorSlmcNo: draft.doctorSlmcNo || '',
          });
        }
      } catch (err: any) {
        setError(err.response?.data?.message || 'Failed to initialize report draft.');
      } finally {
        setLoading(false);
      }
    };

    initReport();
  }, [isOpen, caseType, caseId, existingReport]);

  useEffect(() => {
    if (viewMode === 'PREVIEW') {
      const combined = getCombinedReportData();
      if (combined) {
        const url = getReportPdfBlobUrl(combined);
        setPdfPreviewUrl(url);
      }
    }
  }, [viewMode, formData, reportType, currentReport]);

  if (!isOpen) return null;

  const handleReportTypeChange = async (type: ReportType) => {
    setReportType(type);
    setLoading(true);
    setError(null);
    try {
      const draft = await reportService.autoGenerateDraft(caseType, caseId, type);
      setCurrentReport(draft);
      setFormData({
        courtName: draft.courtName || formData.courtName || '',
        courtCaseNo: draft.courtCaseNo || formData.courtCaseNo || '',
        policeStation: draft.policeStation || formData.policeStation || '',
        policeRefNo: draft.policeRefNo || formData.policeRefNo || '',
        dateOfTrial: draft.dateOfTrial || formData.dateOfTrial || '',
        opinion: draft.opinion || '',
        doctorName: draft.doctorName || formData.doctorName || '',
        doctorDesignation: draft.doctorDesignation || formData.doctorDesignation || '',
        doctorSlmcNo: draft.doctorSlmcNo || formData.doctorSlmcNo || '',
      });
    } catch (err: any) {
      setError(err.response?.data?.message || err.message || 'Failed to switch template.');
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async (statusOverride?: ReportStatus) => {
    if (!currentReport) return;
    setSaving(true);
    setError(null);
    try {
      const payload: ForensicReportDto = {
        ...currentReport,
        reportType,
        courtName: formData.courtName,
        courtCaseNo: formData.courtCaseNo,
        policeStation: formData.policeStation,
        policeRefNo: formData.policeRefNo,
        dateOfTrial: formData.dateOfTrial,
        opinion: formData.opinion,
        doctorName: formData.doctorName,
        doctorDesignation: formData.doctorDesignation,
        doctorSlmcNo: formData.doctorSlmcNo,
      };

      if (statusOverride) {
        payload.status = statusOverride;
      }

      const saved = await reportService.save(payload);
      setCurrentReport(saved);
      if (onReportSaved) onReportSaved();
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to save report');
    } finally {
      setSaving(false);
    }
  };

  const handleStatusTransition = async (nextStatus: ReportStatus) => {
    if (!currentReport?.id) return;
    setSaving(true);
    try {
      await handleSave(nextStatus);
      const updated = await reportService.updateStatus(currentReport.id, nextStatus);
      setCurrentReport(updated);
      if (onReportSaved) onReportSaved();
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to update report status.');
    } finally {
      setSaving(false);
    }
  };

  const handleAmend = async () => {
    if (!currentReport?.id || !amendReason) return;
    setSaving(true);
    try {
      const payload: ForensicReportDto = {
        ...currentReport,
        courtName: formData.courtName,
        courtCaseNo: formData.courtCaseNo,
        opinion: formData.opinion,
        doctorName: formData.doctorName,
      };
      const amended = await reportService.amendReport(currentReport.id, amendReason, payload);
      setCurrentReport(amended);
      setShowAmendInput(false);
      setAmendReason('');
      if (onReportSaved) onReportSaved();
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to amend report');
    } finally {
      setSaving(false);
    }
  };

  const handleDownloadPdf = () => {
    const combined = getCombinedReportData();
    if (combined) {
      generateReportPdf(combined);
    }
  };

  const handlePrintPdf = () => {
    const combined = getCombinedReportData();
    if (combined) {
      printReportPdf(combined);
    }
  };

  const status = currentReport?.status || 'DRAFT';

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl border border-gray-200 w-full max-w-5xl h-[90vh] flex flex-col overflow-hidden">
        
        {/* Modal Header */}
        <div className="px-6 py-4 border-b border-gray-200 bg-gray-50 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2 bg-blue-100 text-blue-600 rounded-lg">
              <FileText className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-gray-900">Forensic Report Generator & Print Preview</h2>
              <p className="text-xs text-gray-500">
                Case Type: {caseType} | Serial: {currentReport?.serialNo || 'Draft'} | Rev v{currentReport?.versionNumber || 1}
              </p>
            </div>
          </div>

          {/* View Mode Toggle Switch */}
          <div className="flex items-center space-x-2 bg-gray-200 p-1 rounded-xl">
            <button
              onClick={() => setViewMode('FORM')}
              className={`flex items-center px-3 py-1.5 text-xs font-bold rounded-lg transition-all ${
                viewMode === 'FORM' ? 'bg-white text-gray-900 shadow-xs' : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              <Edit3 className="w-3.5 h-3.5 mr-1.5" />
              Edit Form
            </button>
            <button
              onClick={() => setViewMode('PREVIEW')}
              className={`flex items-center px-3 py-1.5 text-xs font-bold rounded-lg transition-all ${
                viewMode === 'PREVIEW' ? 'bg-blue-600 text-white shadow-xs' : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              <Eye className="w-3.5 h-3.5 mr-1.5" />
              Print Preview
            </button>
          </div>

          <button onClick={onClose} className="p-1.5 text-gray-400 hover:text-gray-600 rounded-full hover:bg-gray-200">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">
          {error && (
            <div className="p-3 bg-red-50 border-l-4 border-red-500 rounded-r-md flex items-center text-red-700 text-sm">
              <AlertCircle className="w-5 h-5 mr-2 flex-shrink-0 text-red-500" />
              {error}
            </div>
          )}

          {loading ? (
            <div className="flex flex-col items-center justify-center py-12">
              <Loader2 className="w-10 h-10 animate-spin text-blue-600 mb-3" />
              <p className="text-sm text-gray-500">Auto-filling report template from case records...</p>
            </div>
          ) : viewMode === 'PREVIEW' ? (
            /* Live Print Preview Tab */
            <div className="h-full flex flex-col space-y-3">
              <div className="flex items-center justify-between bg-blue-50 p-3 rounded-xl border border-blue-200">
                <div className="flex items-center space-x-2 text-xs text-blue-800 font-semibold">
                  <Eye className="w-4 h-4 text-blue-600" />
                  <span>Live PDF Document Preview (Exact layout to be printed)</span>
                </div>
                <button
                  onClick={handlePrintPdf}
                  className="flex items-center px-3.5 py-1.5 bg-blue-600 text-white text-xs font-bold rounded-lg hover:bg-blue-700 shadow-sm"
                >
                  <Printer className="w-4 h-4 mr-1.5" />
                  Print Document Now
                </button>
              </div>

              <div className="flex-1 border border-gray-300 rounded-xl overflow-hidden bg-gray-100 min-h-[500px]">
                {pdfPreviewUrl ? (
                  <iframe
                    src={pdfPreviewUrl}
                    title="Live Report Print Preview"
                    className="w-full h-full min-h-[550px] border-0"
                  />
                ) : (
                  <div className="flex items-center justify-center h-full text-gray-400 text-sm">
                    Generating print preview...
                  </div>
                )}
              </div>
            </div>
          ) : (
            /* Form Editor Tab */
            <>
              {/* Template Selector & Lifecycle Status Bar */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 bg-gray-50 p-4 rounded-xl border border-gray-200">
                <div>
                  <label className="block text-xs font-semibold text-gray-500 uppercase mb-2">Select Report Template</label>
                  <div className="flex flex-wrap gap-2">
                    {caseType === 'CLINICAL' ? (
                      <>
                        <button
                          type="button"
                          onClick={() => handleReportTypeChange('MLR')}
                          className={`px-3 py-1.5 text-xs font-semibold rounded-lg border ${
                            reportType === 'MLR' ? 'bg-blue-600 text-white border-blue-600' : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-100'
                          }`}
                        >
                          MLR Report
                        </button>
                        <button
                          type="button"
                          onClick={() => handleReportTypeChange('MLEF')}
                          className={`px-3 py-1.5 text-xs font-semibold rounded-lg border ${
                            reportType === 'MLEF' ? 'bg-blue-600 text-white border-blue-600' : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-100'
                          }`}
                        >
                          MLEF Form
                        </button>
                        <button
                          type="button"
                          onClick={() => handleReportTypeChange('CERTIFICATE_OF_RECEIPT')}
                          className={`px-3 py-1.5 text-xs font-semibold rounded-lg border ${
                            reportType === 'CERTIFICATE_OF_RECEIPT' ? 'bg-blue-600 text-white border-blue-600' : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-100'
                          }`}
                        >
                          Certificate of Receipt
                        </button>
                      </>
                    ) : (
                      <>
                        <button
                          type="button"
                          onClick={() => handleReportTypeChange('PMR')}
                          className={`px-3 py-1.5 text-xs font-semibold rounded-lg border ${
                            reportType === 'PMR' ? 'bg-blue-600 text-white border-blue-600' : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-100'
                          }`}
                        >
                          Postmortem (PMR)
                        </button>
                        <button
                          type="button"
                          onClick={() => handleReportTypeChange('CERTIFICATE_OF_RECEIPT')}
                          className={`px-3 py-1.5 text-xs font-semibold rounded-lg border ${
                            reportType === 'CERTIFICATE_OF_RECEIPT' ? 'bg-blue-600 text-white border-blue-600' : 'bg-white text-gray-700 border-gray-300 hover:bg-gray-100'
                          }`}
                        >
                          Certificate of Receipt
                        </button>
                      </>
                    )}
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-gray-500 uppercase mb-2">Status Lifecycle Stage</label>
                  <div className="flex items-center space-x-1 text-xs">
                    <span className={`px-2.5 py-1 rounded-full font-semibold ${status === 'DRAFT' ? 'bg-amber-100 text-amber-800 border border-amber-300' : 'bg-gray-200 text-gray-600'}`}>
                      1. Draft
                    </span>
                    <span>&rarr;</span>
                    <span className={`px-2.5 py-1 rounded-full font-semibold ${status === 'FINALIZED' ? 'bg-blue-100 text-blue-800 border border-blue-300' : 'bg-gray-200 text-gray-600'}`}>
                      2. Finalized
                    </span>
                    <span>&rarr;</span>
                    <span className={`px-2.5 py-1 rounded-full font-semibold ${status === 'DISPATCHED' ? 'bg-purple-100 text-purple-800 border border-purple-300' : 'bg-gray-200 text-gray-600'}`}>
                      3. Dispatched
                    </span>
                    <span>&rarr;</span>
                    <span className={`px-2.5 py-1 rounded-full font-semibold ${status === 'RECEIPT_CONFIRMED' ? 'bg-emerald-100 text-emerald-800 border border-emerald-300' : 'bg-gray-200 text-gray-600'}`}>
                      4. Receipt Confirmed
                    </span>
                  </div>
                </div>
              </div>

              {/* Form Fields */}
              <div className="space-y-4">
                <h3 className="text-sm font-semibold text-gray-900 border-b pb-2 uppercase tracking-wider">Court & Legal References</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Court Name</label>
                    <input
                      type="text"
                      value={formData.courtName}
                      onChange={(e) => setFormData({ ...formData, courtName: e.target.value })}
                      placeholder="e.g. Magistrate Court No 1"
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Court Case No</label>
                    <input
                      type="text"
                      value={formData.courtCaseNo}
                      onChange={(e) => setFormData({ ...formData, courtCaseNo: e.target.value })}
                      placeholder="e.g. MC/9482/2026"
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Date of Trial</label>
                    <input
                      type="date"
                      value={formData.dateOfTrial}
                      onChange={(e) => setFormData({ ...formData, dateOfTrial: e.target.value })}
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Police Station</label>
                    <input
                      type="text"
                      value={formData.policeStation}
                      onChange={(e) => setFormData({ ...formData, policeStation: e.target.value })}
                      placeholder="e.g. Police HQ Division"
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Police Ref No</label>
                    <input
                      type="text"
                      value={formData.policeRefNo}
                      onChange={(e) => setFormData({ ...formData, policeRefNo: e.target.value })}
                      placeholder="e.g. CIB/104/55"
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Report Serial No</label>
                    <input
                      type="text"
                      value={currentReport?.serialNo || ''}
                      readOnly
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-200 bg-gray-100 rounded-md text-gray-600"
                    />
                  </div>
                </div>

                <h3 className="text-sm font-semibold text-gray-900 border-b pb-2 uppercase tracking-wider pt-2">Doctor & Certification Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Doctor Name</label>
                    <input
                      type="text"
                      value={formData.doctorName}
                      onChange={(e) => setFormData({ ...formData, doctorName: e.target.value })}
                      placeholder="Dr. Full Name"
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">Designation</label>
                    <input
                      type="text"
                      value={formData.doctorDesignation}
                      onChange={(e) => setFormData({ ...formData, doctorDesignation: e.target.value })}
                      placeholder="e.g. Judicial Medical Officer"
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                  <div>
                    <label className="block text-xs font-medium text-gray-700">SLMC Registration No</label>
                    <input
                      type="text"
                      value={formData.doctorSlmcNo}
                      onChange={(e) => setFormData({ ...formData, doctorSlmcNo: e.target.value })}
                      placeholder="e.g. SLMC-48201"
                      className="mt-1 w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                    />
                  </div>
                </div>

                <h3 className="text-sm font-semibold text-gray-900 border-b pb-2 uppercase tracking-wider pt-2">Medical Opinion & Findings</h3>
                <div>
                  <textarea
                    rows={4}
                    value={formData.opinion}
                    onChange={(e) => setFormData({ ...formData, opinion: e.target.value })}
                    placeholder="Enter formal medical opinion..."
                    className="w-full px-3 py-2 text-sm border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                  />
                </div>

                {/* Amendment Input Box */}
                {showAmendInput && (
                  <div className="p-4 bg-amber-50 border border-amber-200 rounded-xl space-y-3">
                    <h4 className="text-xs font-bold text-amber-800 uppercase">Create Amended Version (v{(currentReport?.versionNumber || 1) + 1})</h4>
                    <input
                      type="text"
                      value={amendReason}
                      onChange={(e) => setAmendReason(e.target.value)}
                      placeholder="Reason for amendment (e.g., Supplementary toxicology findings attached)..."
                      className="w-full px-3 py-2 text-sm border border-amber-300 rounded-md focus:ring-amber-500 focus:border-amber-500 bg-white"
                    />
                    <div className="flex justify-end space-x-2">
                      <button
                        onClick={() => setShowAmendInput(false)}
                        className="px-3 py-1.5 text-xs text-gray-600 hover:bg-gray-200 rounded-md"
                      >
                        Cancel
                      </button>
                      <button
                        onClick={handleAmend}
                        disabled={!amendReason || saving}
                        className="px-3 py-1.5 text-xs bg-amber-600 text-white rounded-md hover:bg-amber-700 disabled:opacity-50"
                      >
                        Confirm Amendment
                      </button>
                    </div>
                  </div>
                )}
              </div>
            </>
          )}
        </div>

        {/* Modal Footer / Actions */}
        <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center space-x-2">
            <button
              onClick={() => handleSave()}
              disabled={saving || loading}
              className="px-4 py-2 bg-gray-800 text-white text-xs font-semibold rounded-lg hover:bg-gray-900 transition-colors shadow-sm disabled:opacity-50"
            >
              Save Draft
            </button>
            <button
              onClick={handlePrintPdf}
              disabled={loading}
              className="flex items-center px-4 py-2 bg-blue-600 text-white text-xs font-semibold rounded-lg hover:bg-blue-700 transition-colors shadow-sm"
            >
              <Printer className="w-4 h-4 mr-1.5" />
              Print Report
            </button>
            <button
              onClick={handleDownloadPdf}
              disabled={loading}
              className="flex items-center px-4 py-2 bg-emerald-600 text-white text-xs font-semibold rounded-lg hover:bg-emerald-700 transition-colors shadow-sm"
            >
              <Download className="w-4 h-4 mr-1.5" />
              Download PDF
            </button>
          </div>

          <div className="flex items-center space-x-2">
            {status === 'DRAFT' && (
              <button
                onClick={() => handleStatusTransition('FINALIZED')}
                disabled={saving || loading}
                className="flex items-center px-4 py-2 bg-blue-600 text-white text-xs font-semibold rounded-lg hover:bg-blue-700 transition-colors shadow-sm"
              >
                <CheckCircle className="w-4 h-4 mr-1.5" />
                Finalize Report
              </button>
            )}

            {status === 'FINALIZED' && (
              <button
                onClick={() => handleStatusTransition('DISPATCHED')}
                disabled={saving || loading}
                className="flex items-center px-4 py-2 bg-purple-600 text-white text-xs font-semibold rounded-lg hover:bg-purple-700 transition-colors shadow-sm"
              >
                <Send className="w-4 h-4 mr-1.5" />
                Mark Dispatched
              </button>
            )}

            {(status === 'FINALIZED' || status === 'DISPATCHED') && (
              <button
                onClick={() => handleStatusTransition('RECEIPT_CONFIRMED')}
                disabled={saving || loading}
                className="flex items-center px-4 py-2 bg-emerald-600 text-white text-xs font-semibold rounded-lg hover:bg-emerald-700 transition-colors shadow-sm"
              >
                <CheckSquare className="w-4 h-4 mr-1.5" />
                Confirm Receipt
              </button>
            )}

            {status !== 'DRAFT' && !showAmendInput && (
              <button
                onClick={() => setShowAmendInput(true)}
                className="flex items-center px-3 py-2 bg-amber-100 text-amber-800 text-xs font-semibold rounded-lg hover:bg-amber-200 transition-colors border border-amber-300"
              >
                <RefreshCw className="w-3.5 h-3.5 mr-1.5" />
                Amend Version
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
